# Generated by Django 5.1.7 on 2025-05-30 05:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_personalattendancesetting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='personalattendancesetting',
            name='checkout_time',
            field=models.TimeField(default='17:00:00', verbose_name='Giờ ra ca'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personalattendancesetting',
            name='checkin_time',
            field=models.TimeField(verbose_name='Giờ vào ca'),
        ),
        migrations.AlterUniqueTogether(
            name='personalattendancesetting',
            unique_together={('user', 'date')},
        ),
    ]
